# Generated by Django 5.2.6 on 2025-10-02 04:25

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=40),
        ),
    ]
