# Generated by Django 5.2.6 on 2025-10-02 08:11

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=64),
        ),
    ]
