# Generated by Django 5.2.6 on 2025-10-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_expiry_temp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='otp_temp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
