# Generated by Django 5.2.6 on 2025-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_otp_expiry_temp_student_otp_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
