# Generated by Django 5.2.6 on 2025-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
