# Generated by Django 5.2.6 on 2025-10-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_otp_expiry_temp_student_otp_temp'),
        ('university_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='students.admin'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='students.university'),
        ),
        migrations.AlterUniqueTogether(
            name='adminprofile',
            unique_together={('admin', 'university')},
        ),
    ]
