# Generated by Django 5.2.6 on 2025-10-01 22:43

import django.utils.timezone
from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def create_default_superadmin(apps, schema_editor):
    SuperAdmin = apps.get_model('superadmin', 'SuperAdmin')
    if not SuperAdmin.objects.filter(email="seth.mensah@amalitechtraining.org").exists():
        SuperAdmin.objects.create(
            name="Sam Flex",
            email="seth.mensah@amalitechtraining.org",
            phone_number="+233277935236",
            password=make_password("password100"),
            is_staff=True,
            is_superuser=True,
            is_active=True,
            date_joined=django.utils.timezone.now(),
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups this user belongs to.', related_name='superadmin_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='superadmin_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_superadmin),
    ]