# Generated by Django 5.2.6 on 2025-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
