# Generated by Django 5.2.6 on 2025-10-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_superadmin_sms_otp_superadmin_sms_otp_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
