# Generated by Django 5.2.6 on 2025-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('superadmin', '0004_admin_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='superadmin_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='superadmin_set', to='auth.permission'),
        ),
    ]
