# Generated by Django 5.2.6 on 2025-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('superadmin', '0005_alter_superadmin_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this user belongs to.', related_name='superadmin_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='superadmin_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
