from django.urls import path
from .views import (
    AdminLoginView,
    RefreshTokenView,
    AdminCreateView,
    ImportStudentsView,
    AdminListView,
    AdminUpdateView,
    AdminDeleteView,
    CandidateCreateView,
    CandidateListView,
    CandidateUpdateView,
    CandidateDeleteView,
    ElectionCreateView,
    ElectionListView,
    ElectionUpdateView,
    ElectionDeleteView,
)

urlpatterns = [
    path('login/', AdminLoginView.as_view(), name='admin-login'),
    path('refresh-token/', RefreshTokenView.as_view(), name='refresh-token'),
    path('create/', AdminCreateView.as_view(), name='admin-create'),
    path('import-students/', ImportStudentsView.as_view(), name='import-students'),
    path('list/', AdminListView.as_view(), name='admin-list'),
    path('update/<int:pk>/', AdminUpdateView.as_view(), name='admin-update'),
    path('delete/<int:pk>/', AdminDeleteView.as_view(), name='admin-delete'),
    path('candidates/create/', CandidateCreateView.as_view(), name='candidate-create'),
    path('candidates/', CandidateListView.as_view(), name='candidate-list'),
    path('candidates/update/<int:pk>/', CandidateUpdateView.as_view(), name='candidate-update'),
    path('candidates/delete/<int:pk>/', CandidateDeleteView.as_view(), name='candidate-delete'),
    path('elections/create/', ElectionCreateView.as_view(), name='election-create'),
    path('elections/', ElectionListView.as_view(), name='election-list'),
    path('elections/update/<int:pk>/', ElectionUpdateView.as_view(), name='election-update'),
    path('elections/delete/<int:pk>/', ElectionDeleteView.as_view(), name='election-delete'),
]